# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
        
         # Runs a set of commands using the runners shell
      - name: wget
        run: |
          echo beginww
          sudo apt-get install sshpass
          yum -y install sshpass
           wget https://github.com/goharbor/harbor/releases/download/v2.2.0-rc3/harbor-offline-installer-v2.2.0-rc3.tgz 
           sshpass -p AA123456zz scp root@101.200.180.194:/root/test"''$(date +"%Y")''$[$(date +"%j"+$i)] ./harbor-offline-installer-v2.2.0-rc3.tgz

